/*! ****************************************************************************
 * KZlog v2.0.0
 *
 * A minimal lightweight logging library for JavaScript.
 * (you can download it from npm or github repositories)
 * Copyright (c) 2026 Mobilabs <contact@mobilabs.fr> (https://www.mobilabs.fr).
 * Released under the MIT license. You may obtain a copy of the License
 * at: http://www.opensource.org/licenses/mit-license.php).
 * Built from ES6lib v3.0.0-beta.1.7.
 * ************************************************************************** */
const $__ES6GLOB={};!function(e,t){"use strict";"function"==typeof define&&define.amd?define([""],t):"object"==typeof exports?module.exports=t(e):e.KZlog=t(e)}($__ES6GLOB,e=>{"use strict";let t,n;const i={Public:{}};return n=function(e,t){const n=Object.keys(t);for(let i=0;i<n.length;i++)e[n[i]]=t[n[i]]},function(){const n=i.Public,r=e.KZlog;let s;t=function(e,t,n){const i=Object.create(s);return i._library={name:"KZlog",version:"2.0.0"},i.name=e||"unknown!",i.level=t||"trace",i.highlight=!1!==n,i},t.NAME="KZlog",t.VERSION="2.0.0",t._setTestMode=function(){return[]},t.noConflict=function(){return e.KZlog=r,this},s={whoami(){return this._library},help(){const e=["","Prints a log message formatted as: [year-month-day] [level] name message,","Methods:","  help(): print this message,","  version(): return the version number,","  setName(name): set the name","  setLevel(level): set the level","  setHighlight()highlight: set the highlight mode","  trace(msg): print the trace message,","  debug(msg): print the debug message,","  info(msg): print the info message,","  warn(msg): print the warn message,","  error(msg): print the error message,","  fatal(msg): print the fatal message,",""].join("\n");console.log(e)},setName(e){return this.name=e||"unknown!",this},setLevel(e){return this.level=e||"trace",this},setHighlight(e){return this.highlight=!1!==e,this},trace(e){return n.print(this,e,"trace"),this},debug(e){return n.print(this,e,"debug"),this},info(e){return n.print(this,e,"info"),this},warn(e){return n.print(this,e,"warn"),this},error(e){return n.print(this,e,"error"),this},fatal(e){return n.print(this,e,"fatal"),this}}}(),function(){const e=i.Public,t=["trace","debug","info","warn","error","fatal","off"];n(e,{print(e,n,i){const r=t,s=[32,36,34,33,35,31,0],o=new Date;let l,h=`[${o.getFullYear()}-${o.getMonth()+1}-${o.getDate()}  `;if(h+=`${o.getHours()}:${o.getMinutes()}:${o.getSeconds()}:${o.getMilliseconds()}`,h+="]",e.level||(e.level="trace"),void 0===e.highlight&&(e.highlight=!0),r.indexOf(i)>=r.indexOf(e.level)){if(!0===e.highlight){l=`${h} [${`[1;${s[r.indexOf(i)]}m`}${i}${"[0m"}] `,l+=`${e.name}: ${n}`}else l=`${h} [${i}] ${e.name}: ${n}`;console.log(l),"object"==typeof n&&console.log(n)}}})}(),t});export default $__ES6GLOB.KZlog;