/*! ****************************************************************************
 * KZlog v1.0.2
 *
 * A minimal lightweight logging library for JavaScript.
 * (you can download it from npm or github repositories)
 * Copyright (c) 2021 Mobilabs <contact@mobilabs.fr> (http://www.mobilabs.fr).
 * Released under the MIT license. You may obtain a copy of the License
 * at: http://www.opensource.org/licenses/mit-license.php).
 * Built from ES6lib v1.0.12.
 * ************************************************************************** */
const $__ES6GLOB={};!function(e,t){"use strict";"function"==typeof define&&define.amd?define([""],t):"object"==typeof exports?module.exports=t(e):e.KZlog=t(e)}($__ES6GLOB,(e=>{"use strict";let t,n={};return function(){const r=e.KZlog;let i;t=function(e,t,n){const r=Object.create(i);return r._library={name:"KZlog",version:"1.0.2"},r.name=e||"unknown!",r.level=t||"trace",r.highlight=!1!==n,r},t.NAME="KZlog",t.VERSION="1.0.2",t._setTestMode=function(){return[]},t.noConflict=function(){return e.KZlog=r,this},i={whoami(){return this._library},help(){const e=["","Prints a log message formatted as: [year-month-day] [level] name message,","Methods:","  help(): print this message,","  version(): return the version number,","  setName(name): set the name","  setLevel(level): set the level","  setHighlight()highlight: set the highlight mode","  trace(msg): print the trace message,","  debug(msg): print the debug message,","  info(msg): print the info message,","  warn(msg): print the warn message,","  error(msg): print the error message,","  fatal(msg): print the fatal message,",""].join("\n");console.log(e)},setName(e){return this.name=e||"unknown!",this},setLevel(e){return this.level=e||"trace",this},setHighlight(e){return this.highlight=!1!==e,this},trace(e){return n.print(this,e,"trace"),this},debug(e){return n.print(this,e,"debug"),this},info(e){return n.print(this,e,"info"),this},warn(e){return n.print(this,e,"warn"),this},error(e){return n.print(this,e,"error"),this},fatal(e){return n.print(this,e,"fatal"),this}}}(),function(){const e=["trace","debug","info","warn","error","fatal","off"];n={print(t,n,r){const i=e,s=[32,36,34,33,35,31,0],o=new Date;let h,l=`[${o.getFullYear()}-${o.getMonth()+1}-${o.getDate()}  `;if(l+=`${o.getHours()}:${o.getMinutes()}:${o.getSeconds()}:${o.getMilliseconds()}`,l+="]",t.level||(t.level="trace"),void 0===t.highlight&&(t.highlight=!0),i.indexOf(r)>=i.indexOf(t.level)){if(!0===t.highlight){h=`${l} [${`[1;${s[i.indexOf(r)]}m`}${r}${"[0m"}] `,h+=`${t.name}: ${n}`}else h=`${l} [${r}] ${t.name}: ${n}`;console.log(h),"object"==typeof n&&console.log(n)}}}}(),t}));export default $__ES6GLOB.KZlog;